[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.18"
via_ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@balancer-labs/v2-interfaces/=lib/balancer-v2-monorepo/pkg/interfaces/",
    "@balancer-labs/v2-vault/=lib/balancer-v2-monorepo/pkg/vault/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-periphery/contracts/interfaces/=lib/v3-periphery/contracts/interfaces/",
    "@uniswap/v3-core/contracts/interfaces/=lib/v3-core/contracts/interfaces/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
]